version: "3.0"

services:
  nginx:
    ports:
      - "80:80"
  node-express-api:
    build:
      args:
        NODE_ENV: production
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PWD=${MONGO_PWD}
      - REDIS_SECRET=${REDIS_SECRET}
    command: yarn start
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
