version: "3.0"

services:
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
  node-express-api:
    build:
      context: .
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.10
    restart: unless-stopped
    volumes:
      - db-data:/data/db
  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data
      - /etc/localtime:/etc/localtime:ro
volumes:
  db-data:
  redis-data:
